### ISSUE TITLE
Add Trema Eclipse to Eclipse Marketplace

### ISSUE THREAD

**Issue by stadler** [netceteragroup/trema-eclipse#9]
There should be an entry for Trema in the Eclipse Marketplace to ensure that people who are looking for such software also find it:
https://marketplace.eclipse.org/

**Comment by marcelstoer** [comment]
Good point! Maybe the rat pack can help us create nice attractive descriptions that aren't too technical.

**Comment by stadler** [comment]
Done: https://marketplace.eclipse.org/content/trema
Documented here: http://netceteragroup.github.io/trema-eclipse/installation.html
